version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: marcus-shop
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
